<div class='main'>
        <h2 style="margin-top:0px">Tbl_userinfo اطلاعات</h2>
        <table class="table">
	    <tr><td>StatusPic</td><td><?php echo $StatusPic; ?></td></tr>
	    <tr><td>IdUser</td><td><?php echo $IdUser; ?></td></tr>
	    <tr><td>Birthday</td><td><?php echo $Birthday; ?></td></tr>
	    <tr><td>State</td><td><?php echo $State; ?></td></tr>
	    <tr><td>City</td><td><?php echo $City; ?></td></tr>
	    <tr><td>MaridgeState</td><td><?php echo $MaridgeState; ?></td></tr>
	    <tr><td>Education</td><td><?php echo $Education; ?></td></tr>
	    <tr><td>FieldEducation</td><td><?php echo $FieldEducation; ?></td></tr>
	    <tr><td>JobState</td><td><?php echo $JobState; ?></td></tr>
	    <tr><td>JobTitle</td><td><?php echo $JobTitle; ?></td></tr>
	    <tr><td>FamilyIncome</td><td><?php echo $FamilyIncome; ?></td></tr>
	    <tr><td>Income</td><td><?php echo $Income; ?></td></tr>
	    <tr><td>HomeState</td><td><?php echo $HomeState; ?></td></tr>
	    <tr><td>CarState</td><td><?php echo $CarState; ?></td></tr>
	    <tr><td>Height</td><td><?php echo $Height; ?></td></tr>
	    <tr><td>Weight</td><td><?php echo $Weight; ?></td></tr>
	    <tr><td>SkinColor</td><td><?php echo $SkinColor; ?></td></tr>
	    <tr><td>Religion</td><td><?php echo $Religion; ?></td></tr>
	    <tr><td>Belief</td><td><?php echo $Belief; ?></td></tr>
	    <tr><td>Hijab</td><td><?php echo $Hijab; ?></td></tr>
	    <tr><td>HealthState</td><td><?php echo $HealthState; ?></td></tr>
	    <tr><td>HealthInfo</td><td><?php echo $HealthInfo; ?></td></tr>
	    <tr><td>Iam</td><td><?php echo $Iam; ?></td></tr>
	    <tr><td>WifeIs</td><td><?php echo $WifeIs; ?></td></tr>
	    <tr><td>TypePerson</td><td><?php echo $TypePerson; ?></td></tr>
	    <tr><td>MaridgeScale</td><td><?php echo $MaridgeScale; ?></td></tr>
	    <tr><td>CountFriends</td><td><?php echo $CountFriends; ?></td></tr>
	    <tr><td>LocationLife</td><td><?php echo $LocationLife; ?></td></tr>
	    <tr><td>Pretty</td><td><?php echo $Pretty; ?></td></tr>
	    <tr><td>Tip</td><td><?php echo $Tip; ?></td></tr>
	    <tr><td>LifeStyle</td><td><?php echo $LifeStyle; ?></td></tr>
	    <tr><td>LocationSelfLife</td><td><?php echo $LocationSelfLife; ?></td></tr>
	    <tr><td>UseCigaret</td><td><?php echo $UseCigaret; ?></td></tr>
	    <tr><td>UseAlcohol</td><td><?php echo $UseAlcohol; ?></td></tr>
	    <tr><td>Emigration</td><td><?php echo $Emigration; ?></td></tr>
	    <tr><td>Dowry</td><td><?php echo $Dowry; ?></td></tr>
	    <tr><td>Ofmarriage</td><td><?php echo $Ofmarriage; ?></td></tr>
	    <tr><td>MyOccupation</td><td><?php echo $MyOccupation; ?></td></tr>
	    <tr><td>MyEducation</td><td><?php echo $MyEducation; ?></td></tr>
	    <tr><td>WifeOccupation</td><td><?php echo $WifeOccupation; ?></td></tr>
	    <tr><td>WifeEducation</td><td><?php echo $WifeEducation; ?></td></tr>
	    <tr><td>StudyScale</td><td><?php echo $StudyScale; ?></td></tr>
	    <tr><td>SportScale</td><td><?php echo $SportScale; ?></td></tr>
	    <tr><td>MateAge</td><td><?php echo $MateAge; ?></td></tr>
	    <tr><td>MateMarridge</td><td><?php echo $MateMarridge; ?></td></tr>
	    <tr><td>MateLocation</td><td><?php echo $MateLocation; ?></td></tr>
	    <tr><td>MateEducation</td><td><?php echo $MateEducation; ?></td></tr>
	    <tr><td>MateFatherEducation</td><td><?php echo $MateFatherEducation; ?></td></tr>
	    <tr><td>MateMotherEducation</td><td><?php echo $MateMotherEducation; ?></td></tr>
	    <tr><td>FatherEducation</td><td><?php echo $FatherEducation; ?></td></tr>
	    <tr><td>MatherEducation</td><td><?php echo $MatherEducation; ?></td></tr>
	    <tr><td>FatherNationality</td><td><?php echo $FatherNationality; ?></td></tr>
	    <tr><td>MatherNationality</td><td><?php echo $MatherNationality; ?></td></tr>
	    <tr><td>AtSon</td><td><?php echo $AtSon; ?></td></tr>
	    <tr><td>CountBrother</td><td><?php echo $CountBrother; ?></td></tr>
	    <tr><td>CountSister</td><td><?php echo $CountSister; ?></td></tr>
	    <tr><td>MarridgeBroSis</td><td><?php echo $MarridgeBroSis; ?></td></tr>
	    <tr><td>CountChildren</td><td><?php echo $CountChildren; ?></td></tr>
	    <tr><td>AgeBigChild</td><td><?php echo $AgeBigChild; ?></td></tr>
	    <tr><td>CellPhone</td><td><?php echo $CellPhone; ?></td></tr>
	    <tr><td>Pic</td><td><?php echo $Pic; ?></td></tr>
	    <tr><td>MojaradWife</td><td><?php echo $MojaradWife; ?></td></tr>
	    <tr><td>TalaghWife</td><td><?php echo $TalaghWife; ?></td></tr>
	    <tr><td>DeadWife</td><td><?php echo $DeadWife; ?></td></tr>
	    <tr><td>Hamshahri</td><td><?php echo $Hamshahri; ?></td></tr>
	    <tr><td>HamOstani</td><td><?php echo $HamOstani; ?></td></tr>
	    <tr><td>HamVatan</td><td><?php echo $HamVatan; ?></td></tr>
	    <tr><td>Kharej</td><td><?php echo $Kharej; ?></td></tr>
	    <tr><td>MateAgeTo</td><td><?php echo $MateAgeTo; ?></td></tr>
	    <tr><td>MateEducationTo</td><td><?php echo $MateEducationTo; ?></td></tr>
	    <tr><td>MateFatherEducationTo</td><td><?php echo $MateFatherEducationTo; ?></td></tr>
	    <tr><td>MateMotherEducationTo</td><td><?php echo $MateMotherEducationTo; ?></td></tr>
	    <tr><td>GhadAs</td><td><?php echo $GhadAs; ?></td></tr>
	    <tr><td>GhadTa</td><td><?php echo $GhadTa; ?></td></tr>
	    <tr><td>VaznAs</td><td><?php echo $VaznAs; ?></td></tr>
	    <tr><td>VaznTa</td><td><?php echo $VaznTa; ?></td></tr>
	    <tr><td>Sefid</td><td><?php echo $Sefid; ?></td></tr>
	    <tr><td>SabzeRoshan</td><td><?php echo $SabzeRoshan; ?></td></tr>
	    <tr><td>SabzeTire</td><td><?php echo $SabzeTire; ?></td></tr>
	    <tr><td>DarAmadFamilyAs</td><td><?php echo $DarAmadFamilyAs; ?></td></tr>
	    <tr><td>DarAmadFamilyTa</td><td><?php echo $DarAmadFamilyTa; ?></td></tr>
	    <tr><td>DaramadHamsarAs</td><td><?php echo $DaramadHamsarAs; ?></td></tr>
	    <tr><td>DaramadHamsarTa</td><td><?php echo $DaramadHamsarTa; ?></td></tr>
	    <tr><td>HomeNadarad</td><td><?php echo $HomeNadarad; ?></td></tr>
	    <tr><td>HomeDarad</td><td><?php echo $HomeDarad; ?></td></tr>
	    <tr><td>CarDarad</td><td><?php echo $CarDarad; ?></td></tr>
	    <tr><td>CarNadarad</td><td><?php echo $CarNadarad; ?></td></tr>
	    <tr><td>Sheea</td><td><?php echo $Sheea; ?></td></tr>
	    <tr><td>Soni</td><td><?php echo $Soni; ?></td></tr>
	    <tr><td>DinMasih</td><td><?php echo $DinMasih; ?></td></tr>
	    <tr><td>DinYahod</td><td><?php echo $DinYahod; ?></td></tr>
	    <tr><td>MazhabiMoghayad</td><td><?php echo $MazhabiMoghayad; ?></td></tr>
	    <tr><td>Mazhabi</td><td><?php echo $Mazhabi; ?></td></tr>
	    <tr><td>UnMazhabi</td><td><?php echo $UnMazhabi; ?></td></tr>
	    <tr><td>MohajabeChadori</td><td><?php echo $MohajabeChadori; ?></td></tr>
	    <tr><td>BadHejab</td><td><?php echo $BadHejab; ?></td></tr>
	    <tr><td>Bihejab</td><td><?php echo $Bihejab; ?></td></tr>
	    <tr><td>Salem</td><td><?php echo $Salem; ?></td></tr>
	    <tr><td>BimarKhas</td><td><?php echo $BimarKhas; ?></td></tr>
	    <tr><td>NaghsOzv</td><td><?php echo $NaghsOzv; ?></td></tr>
	    <tr><td>Daroongara</td><td><?php echo $Daroongara; ?></td></tr>
	    <tr><td>Boroongara</td><td><?php echo $Boroongara; ?></td></tr>
	    <tr><td>Fars</td><td><?php echo $Fars; ?></td></tr>
	    <tr><td>Tork</td><td><?php echo $Tork; ?></td></tr>
	    <tr><td>Kord</td><td><?php echo $Kord; ?></td></tr>
	    <tr><td>Lor</td><td><?php echo $Lor; ?></td></tr>
	    <tr><td>Balooch</td><td><?php echo $Balooch; ?></td></tr>
	    <tr><td>Mazandaran</td><td><?php echo $Mazandaran; ?></td></tr>
	    <tr><td>Gilak</td><td><?php echo $Gilak; ?></td></tr>
	    <tr><td>Arab</td><td><?php echo $Arab; ?></td></tr>
	    <tr><td>Sayer</td><td><?php echo $Sayer; ?></td></tr>
	    <tr><td>FarzandNadarad</td><td><?php echo $FarzandNadarad; ?></td></tr>
	    <tr><td>FarzandDarad</td><td><?php echo $FarzandDarad; ?></td></tr>
	    <tr><td>SigarNadrad</td><td><?php echo $SigarNadrad; ?></td></tr>
	    <tr><td>SigarDarad</td><td><?php echo $SigarDarad; ?></td></tr>
	    <tr><td>AlcolNadarad</td><td><?php echo $AlcolNadarad; ?></td></tr>
	    <tr><td>AlcolDarad</td><td><?php echo $AlcolDarad; ?></td></tr>
	    <tr><td>MohajeratDarad</td><td><?php echo $MohajeratDarad; ?></td></tr>
	    <tr><td>MohajeratNadarad</td><td><?php echo $MohajeratNadarad; ?></td></tr>
	    <tr><td>TedadBaraKha</td><td><?php echo $TedadBaraKha; ?></td></tr>
	    <tr><td>Bikar</td><td><?php echo $Bikar; ?></td></tr>
	    <tr><td>Shaghel</td><td><?php echo $Shaghel; ?></td></tr>
	    <tr><td>Daneshjoo</td><td><?php echo $Daneshjoo; ?></td></tr>
	    <tr><td>Complete_Profile</td><td><?php echo $Complete_Profile; ?></td></tr>
	    <tr><td>MahojabeKamel</td><td><?php echo $MahojabeKamel; ?></td></tr>
	    <tr><td></td><td><a href="<?php echo site_url('userinfo') ?>" class="btn btn-default">بازگشت</button></td></tr>
	</table>
    </div>